
/*
 * 
 */

package com.ligitalsoft.defcat.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.10
 * Mon Aug 22 14:10:33 CST 2011
 * Generated source version: 2.2.10
 * 
 */  


@WebServiceClient(name = "CatalogWebServiceImplService", 
                  wsdlLocation = "http://localhost:8888/catalog/webservice/catalogWebService?wsdl",
                  targetNamespace = "http://webservice.defcat.ligitalsoft.com/") 
public class CatalogWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.defcat.ligitalsoft.com/", "CatalogWebServiceImplService");
    public final static QName CatalogWebServiceImplPort = new QName("http://webservice.defcat.ligitalsoft.com/", "CatalogWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.100.201:8188/catalog/webservice/catalogWebService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8888/catalog/webservice/catalogWebService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public CatalogWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CatalogWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CatalogWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns CatalogWebService
     */
    @WebEndpoint(name = "CatalogWebServiceImplPort")
    public CatalogWebService getCatalogWebServiceImplPort() {
        return super.getPort(CatalogWebServiceImplPort, CatalogWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CatalogWebService
     */
    @WebEndpoint(name = "CatalogWebServiceImplPort")
    public CatalogWebService getCatalogWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(CatalogWebServiceImplPort, CatalogWebService.class, features);
    }

}
