
/*
 * 
 */

package com.ligitalsoft.cloudcenter.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.10
 * Mon Jun 20 16:57:42 CST 2011
 * Generated source version: 2.2.10
 * 
 */


@WebServiceClient(name = "DeployerWebServiceImpService", 
                  wsdlLocation = "http://localhost:8080/iSwapDeployer/DeployerWebService?wsdl",
                  targetNamespace = "http://webservice.cloudcenter.ligitalsoft.com/") 
public class DeployerWebServiceImpService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.cloudcenter.ligitalsoft.com/", "DeployerWebServiceImpService");
    public final static QName DeployerWebServiceImpPort = new QName("http://webservice.cloudcenter.ligitalsoft.com/", "DeployerWebServiceImpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/iSwapDeployer/DeployerWebService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/iSwapDeployer/DeployerWebService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public DeployerWebServiceImpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DeployerWebServiceImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeployerWebServiceImpService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns DeployerWebService
     */
    @WebEndpoint(name = "DeployerWebServiceImpPort")
    public DeployerWebService getDeployerWebServiceImpPort() {
        return super.getPort(DeployerWebServiceImpPort, DeployerWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeployerWebService
     */
    @WebEndpoint(name = "DeployerWebServiceImpPort")
    public DeployerWebService getDeployerWebServiceImpPort(WebServiceFeature... features) {
        return super.getPort(DeployerWebServiceImpPort, DeployerWebService.class, features);
    }

}
