package com.ligitalsoft.cloudcenter.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.2.10 Mon Jun 20 16:57:42 CST 2011 Generated source version: 2.2.10
 */

public final class DeployerWebServiceClient {

    private static final QName SERVICE_NAME = new QName("http://webservice.cloudcenter.ligitalsoft.com/",
                    "DeployerWebServiceImpService");

    private DeployerWebServiceClient() {
    }

    public static DeployerWebService getDeployerWebService(String url) {
        URL u = null;
        try {
            u = new URL(url);
        } catch (MalformedURLException e) {
            throw new RuntimeException("不能得到service");
        }
        DeployerWebServiceImpService ss = new DeployerWebServiceImpService(u, SERVICE_NAME);
        DeployerWebService port = ss.getDeployerWebServiceImpPort();
        return port;
    }
    public static void main(String args[]) throws Exception {
        getDeployerWebService("http://localhost:8888/iSwapDeployer/DeployerWebService?wsdl").deploy("192.168.66.202");
    }

}
